version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgresql
            host: postgres
            database: mydatabase
            user: postgres
            password: password
    ports:
      - "4466:4466"

volumes:
  postgres-data: